# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Clean install
      run: npm ci

    - name: Run dbs_arweave
      run: npm start &
      env:
        ACCEPTED_PAYMENTS: ethereum,matic,boba,boba-eth
        BUNDLR_URI: https://devnet.bundlr.network
        PORT: 8081
        SQLITE_DB_PATH: db
        REGISTRATION_INTERVAL: 300000
        DBS_URI: DEBUG
        SELF_URI: https://localhost

    - name: Wait for dbs_arweave to start
      run: sleep 5

    - name: Run tests
      run: npm test
